### ISSUE TITLE
history data

### ISSUE THREAD

**Issue by stonebb** [mathors/2019-nCoV#1]
Thank you for your work . Do u have the history data , I see that we only have the today’s data, IF we want the history data, what should l do?

**Comment by wmathor** [comment]
> Thank you for your work . Do u have the history data , I see that we only have the today’s data, IF we want the history data, what should l do?

Sorry, I have only saved the data from January 29 to February 3. If you need earlier data, you can look it up again on Github, especially wuhan2020. Maybe they have saved it

**Comment by wmathor** [comment]
> Thank you for your work . Do u have the history data , I see that we only have the today’s data, IF we want the history data, what should l do?

sorry, I forgot to upload the history data, now you can download the Excel file
