### ISSUE TITLE
历史数据怎么下载呢？

### ISSUE THREAD

**Issue by grainw** [mathors/2019-nCoV#2]
你好能提供一下之前跑德历史数据吗？

**Comment by wmathor** [comment]
> 你好能提供一下之前跑德历史数据吗？

已上传，之前更新的时候忘记放这个excel了

**Comment by grainw** [comment]
谢谢，发现疑似的数据好像都是0呢

**Comment by wmathor** [comment]
> 谢谢，发现疑似的数据好像都是0呢

大部分确实是0，这个我也没办法，我爬的丁香医生的数据接口里面就是这样的
