### ISSUE TITLE
运行

### ISSUE THREAD

**Issue by wjvzbr** [mathors/2019-nCoV#6]
运行exe之后dos里没有反应呀

**Comment by wmathor** [comment]
> 运行exe之后dos里没有反应呀

接口又挂了，我正在找别的接口，改好了程序马上push

**Comment by wjvzbr** [comment]
嗯呐 感谢大佬

**Comment by wjvzbr** [comment]
我也在找 感觉接口特别不稳定

**Comment by wmathor** [comment]
是的，之前比较好的接口是丁香医生的，前天开始丁香医生的不能用了，我就换了天气api的，结果天气api昨天下午开始又不能用了，我问他们客服，他们说不免费开放了

**Comment by wmathor** [comment]
> 运行exe之后dos里没有反应呀

改好了，船新的版本

**Comment by wjvzbr** [comment]
很强大

**Comment by wjvzbr** [comment]
赞赞赞~~~

**Comment by wmathor** [comment]
> 赞赞赞~~~

刚刚又push了一次，修正了显示的问题
感谢使用，如有问题欢迎再Issue
